/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FramesSlugRouteImport } from './routes/frames.$slug'
import { Route as FramesSlugIndexRouteImport } from './routes/frames.$slug/index'
import { Route as FramesSlugOrderRouteImport } from './routes/frames.$slug/order'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FramesSlugRoute = FramesSlugRouteImport.update({
  id: '/frames/$slug',
  path: '/frames/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FramesSlugIndexRoute = FramesSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FramesSlugRoute,
} as any)
const FramesSlugOrderRoute = FramesSlugOrderRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => FramesSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/catalog': typeof CatalogRoute
  '/contact': typeof ContactRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/frames/$slug': typeof FramesSlugRouteWithChildren
  '/frames/$slug/order': typeof FramesSlugOrderRoute
  '/frames/$slug/': typeof FramesSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/catalog': typeof CatalogRoute
  '/contact': typeof ContactRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/frames/$slug/order': typeof FramesSlugOrderRoute
  '/frames/$slug': typeof FramesSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/catalog': typeof CatalogRoute
  '/contact': typeof ContactRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/frames/$slug': typeof FramesSlugRouteWithChildren
  '/frames/$slug/order': typeof FramesSlugOrderRoute
  '/frames/$slug/': typeof FramesSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/catalog'
    | '/contact'
    | '/sitemap.xml'
    | '/frames/$slug'
    | '/frames/$slug/order'
    | '/frames/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/catalog'
    | '/contact'
    | '/sitemap.xml'
    | '/frames/$slug/order'
    | '/frames/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/catalog'
    | '/contact'
    | '/sitemap.xml'
    | '/frames/$slug'
    | '/frames/$slug/order'
    | '/frames/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CatalogRoute: typeof CatalogRoute
  ContactRoute: typeof ContactRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  FramesSlugRoute: typeof FramesSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frames/$slug': {
      id: '/frames/$slug'
      path: '/frames/$slug'
      fullPath: '/frames/$slug'
      preLoaderRoute: typeof FramesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frames/$slug/': {
      id: '/frames/$slug/'
      path: '/'
      fullPath: '/frames/$slug/'
      preLoaderRoute: typeof FramesSlugIndexRouteImport
      parentRoute: typeof FramesSlugRoute
    }
    '/frames/$slug/order': {
      id: '/frames/$slug/order'
      path: '/order'
      fullPath: '/frames/$slug/order'
      preLoaderRoute: typeof FramesSlugOrderRouteImport
      parentRoute: typeof FramesSlugRoute
    }
  }
}

interface FramesSlugRouteChildren {
  FramesSlugOrderRoute: typeof FramesSlugOrderRoute
  FramesSlugIndexRoute: typeof FramesSlugIndexRoute
}

const FramesSlugRouteChildren: FramesSlugRouteChildren = {
  FramesSlugOrderRoute: FramesSlugOrderRoute,
  FramesSlugIndexRoute: FramesSlugIndexRoute,
}

const FramesSlugRouteWithChildren = FramesSlugRoute._addFileChildren(
  FramesSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CatalogRoute: CatalogRoute,
  ContactRoute: ContactRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  FramesSlugRoute: FramesSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
